// Major world cities with IANA timezone identifiers
const CITIES = [
  // Korea / Japan / East Asia
  { name: "Seoul", country: "대한민국", tz: "Asia/Seoul" },
  { name: "서울", country: "대한민국", tz: "Asia/Seoul" },
  { name: "Busan", country: "대한민국", tz: "Asia/Seoul" },
  { name: "부산", country: "대한민국", tz: "Asia/Seoul" },
  { name: "Tokyo", country: "일본", tz: "Asia/Tokyo" },
  { name: "도쿄", country: "일본", tz: "Asia/Tokyo" },
  { name: "Osaka", country: "일본", tz: "Asia/Tokyo" },
  { name: "오사카", country: "일본", tz: "Asia/Tokyo" },
  { name: "Beijing", country: "중국", tz: "Asia/Shanghai" },
  { name: "베이징", country: "중국", tz: "Asia/Shanghai" },
  { name: "Shanghai", country: "중국", tz: "Asia/Shanghai" },
  { name: "상하이", country: "중국", tz: "Asia/Shanghai" },
  { name: "Hong Kong", country: "홍콩", tz: "Asia/Hong_Kong" },
  { name: "홍콩", country: "홍콩", tz: "Asia/Hong_Kong" },
  { name: "Taipei", country: "대만", tz: "Asia/Taipei" },
  { name: "타이베이", country: "대만", tz: "Asia/Taipei" },
  { name: "Singapore", country: "싱가포르", tz: "Asia/Singapore" },
  { name: "싱가포르", country: "싱가포르", tz: "Asia/Singapore" },

  // Southeast Asia
  { name: "Bangkok", country: "태국", tz: "Asia/Bangkok" },
  { name: "방콕", country: "태국", tz: "Asia/Bangkok" },
  { name: "Jakarta", country: "인도네시아", tz: "Asia/Jakarta" },
  { name: "자카르타", country: "인도네시아", tz: "Asia/Jakarta" },
  { name: "Manila", country: "필리핀", tz: "Asia/Manila" },
  { name: "마닐라", country: "필리핀", tz: "Asia/Manila" },
  { name: "Ho Chi Minh City", country: "베트남", tz: "Asia/Ho_Chi_Minh" },
  { name: "호치민", country: "베트남", tz: "Asia/Ho_Chi_Minh" },
  { name: "Hanoi", country: "베트남", tz: "Asia/Bangkok" },
  { name: "하노이", country: "베트남", tz: "Asia/Bangkok" },
  { name: "Kuala Lumpur", country: "말레이시아", tz: "Asia/Kuala_Lumpur" },
  { name: "쿠알라룸푸르", country: "말레이시아", tz: "Asia/Kuala_Lumpur" },

  // South Asia
  { name: "Mumbai", country: "인도", tz: "Asia/Kolkata" },
  { name: "뭄바이", country: "인도", tz: "Asia/Kolkata" },
  { name: "Delhi", country: "인도", tz: "Asia/Kolkata" },
  { name: "델리", country: "인도", tz: "Asia/Kolkata" },
  { name: "New Delhi", country: "인도", tz: "Asia/Kolkata" },
  { name: "뉴델리", country: "인도", tz: "Asia/Kolkata" },
  { name: "Kolkata", country: "인도", tz: "Asia/Kolkata" },
  { name: "콜카타", country: "인도", tz: "Asia/Kolkata" },
  { name: "Dhaka", country: "방글라데시", tz: "Asia/Dhaka" },
  { name: "다카", country: "방글라데시", tz: "Asia/Dhaka" },
  { name: "Karachi", country: "파키스탄", tz: "Asia/Karachi" },
  { name: "카라치", country: "파키스탄", tz: "Asia/Karachi" },

  // Middle East / Central Asia
  { name: "Dubai", country: "UAE", tz: "Asia/Dubai" },
  { name: "두바이", country: "UAE", tz: "Asia/Dubai" },
  { name: "Abu Dhabi", country: "UAE", tz: "Asia/Dubai" },
  { name: "아부다비", country: "UAE", tz: "Asia/Dubai" },
  { name: "Riyadh", country: "사우디아라비아", tz: "Asia/Riyadh" },
  { name: "리야드", country: "사우디아라비아", tz: "Asia/Riyadh" },
  { name: "Tehran", country: "이란", tz: "Asia/Tehran" },
  { name: "테헤란", country: "이란", tz: "Asia/Tehran" },
  { name: "Istanbul", country: "튀르키예", tz: "Europe/Istanbul" },
  { name: "이스탄불", country: "튀르키예", tz: "Europe/Istanbul" },
  { name: "Tel Aviv", country: "이스라엘", tz: "Asia/Jerusalem" },
  { name: "텔아비브", country: "이스라엘", tz: "Asia/Jerusalem" },
  { name: "Tashkent", country: "우즈베키스탄", tz: "Asia/Tashkent" },
  { name: "타슈켄트", country: "우즈베키스탄", tz: "Asia/Tashkent" },

  // Europe
  { name: "London", country: "영국", tz: "Europe/London" },
  { name: "런던", country: "영국", tz: "Europe/London" },
  { name: "Paris", country: "프랑스", tz: "Europe/Paris" },
  { name: "파리", country: "프랑스", tz: "Europe/Paris" },
  { name: "Berlin", country: "독일", tz: "Europe/Berlin" },
  { name: "베를린", country: "독일", tz: "Europe/Berlin" },
  { name: "Amsterdam", country: "네덜란드", tz: "Europe/Amsterdam" },
  { name: "암스테르담", country: "네덜란드", tz: "Europe/Amsterdam" },
  { name: "Madrid", country: "스페인", tz: "Europe/Madrid" },
  { name: "마드리드", country: "스페인", tz: "Europe/Madrid" },
  { name: "Rome", country: "이탈리아", tz: "Europe/Rome" },
  { name: "로마", country: "이탈리아", tz: "Europe/Rome" },
  { name: "Milan", country: "이탈리아", tz: "Europe/Rome" },
  { name: "밀라노", country: "이탈리아", tz: "Europe/Rome" },
  { name: "Vienna", country: "오스트리아", tz: "Europe/Vienna" },
  { name: "빈", country: "오스트리아", tz: "Europe/Vienna" },
  { name: "Zurich", country: "스위스", tz: "Europe/Zurich" },
  { name: "취리히", country: "스위스", tz: "Europe/Zurich" },
  { name: "Stockholm", country: "스웨덴", tz: "Europe/Stockholm" },
  { name: "스톡홀름", country: "스웨덴", tz: "Europe/Stockholm" },
  { name: "Oslo", country: "노르웨이", tz: "Europe/Oslo" },
  { name: "오슬로", country: "노르웨이", tz: "Europe/Oslo" },
  { name: "Copenhagen", country: "덴마크", tz: "Europe/Copenhagen" },
  { name: "코펜하겐", country: "덴마크", tz: "Europe/Copenhagen" },
  { name: "Helsinki", country: "핀란드", tz: "Europe/Helsinki" },
  { name: "헬싱키", country: "핀란드", tz: "Europe/Helsinki" },
  { name: "Warsaw", country: "폴란드", tz: "Europe/Warsaw" },
  { name: "바르샤바", country: "폴란드", tz: "Europe/Warsaw" },
  { name: "Prague", country: "체코", tz: "Europe/Prague" },
  { name: "프라하", country: "체코", tz: "Europe/Prague" },
  { name: "Budapest", country: "헝가리", tz: "Europe/Budapest" },
  { name: "부다페스트", country: "헝가리", tz: "Europe/Budapest" },
  { name: "Athens", country: "그리스", tz: "Europe/Athens" },
  { name: "아테네", country: "그리스", tz: "Europe/Athens" },
  { name: "Moscow", country: "러시아", tz: "Europe/Moscow" },
  { name: "모스크바", country: "러시아", tz: "Europe/Moscow" },
  { name: "St. Petersburg", country: "러시아", tz: "Europe/Moscow" },
  { name: "상트페테르부르크", country: "러시아", tz: "Europe/Moscow" },
  { name: "Lisbon", country: "포르투갈", tz: "Europe/Lisbon" },
  { name: "리스본", country: "포르투갈", tz: "Europe/Lisbon" },
  { name: "Brussels", country: "벨기에", tz: "Europe/Brussels" },
  { name: "브뤼셀", country: "벨기에", tz: "Europe/Brussels" },
  { name: "Bucharest", country: "루마니아", tz: "Europe/Bucharest" },
  { name: "부쿠레슈티", country: "루마니아", tz: "Europe/Bucharest" },
  { name: "Kiev", country: "우크라이나", tz: "Europe/Kiev" },
  { name: "키이우", country: "우크라이나", tz: "Europe/Kiev" },
  { name: "Dublin", country: "아일랜드", tz: "Europe/Dublin" },
  { name: "더블린", country: "아일랜드", tz: "Europe/Dublin" },

  // Africa
  { name: "Cairo", country: "이집트", tz: "Africa/Cairo" },
  { name: "카이로", country: "이집트", tz: "Africa/Cairo" },
  { name: "Lagos", country: "나이지리아", tz: "Africa/Lagos" },
  { name: "라고스", country: "나이지리아", tz: "Africa/Lagos" },
  { name: "Nairobi", country: "케냐", tz: "Africa/Nairobi" },
  { name: "나이로비", country: "케냐", tz: "Africa/Nairobi" },
  { name: "Johannesburg", country: "남아프리카", tz: "Africa/Johannesburg" },
  { name: "요하네스버그", country: "남아프리카", tz: "Africa/Johannesburg" },
  { name: "Casablanca", country: "모로코", tz: "Africa/Casablanca" },
  { name: "카사블랑카", country: "모로코", tz: "Africa/Casablanca" },

  // Americas - North
  { name: "New York", country: "미국", tz: "America/New_York" },
  { name: "뉴욕", country: "미국", tz: "America/New_York" },
  { name: "Los Angeles", country: "미국", tz: "America/Los_Angeles" },
  { name: "로스앤젤레스", country: "미국", tz: "America/Los_Angeles" },
  { name: "LA", country: "미국", tz: "America/Los_Angeles" },
  { name: "Chicago", country: "미국", tz: "America/Chicago" },
  { name: "시카고", country: "미국", tz: "America/Chicago" },
  { name: "Houston", country: "미국", tz: "America/Chicago" },
  { name: "휴스턴", country: "미국", tz: "America/Chicago" },
  { name: "Dallas", country: "미국", tz: "America/Chicago" },
  { name: "달라스", country: "미국", tz: "America/Chicago" },
  { name: "Phoenix", country: "미국", tz: "America/Phoenix" },
  { name: "피닉스", country: "미국", tz: "America/Phoenix" },
  { name: "Denver", country: "미국", tz: "America/Denver" },
  { name: "덴버", country: "미국", tz: "America/Denver" },
  { name: "Seattle", country: "미국", tz: "America/Los_Angeles" },
  { name: "시애틀", country: "미국", tz: "America/Los_Angeles" },
  { name: "San Francisco", country: "미국", tz: "America/Los_Angeles" },
  { name: "샌프란시스코", country: "미국", tz: "America/Los_Angeles" },
  { name: "Miami", country: "미국", tz: "America/New_York" },
  { name: "마이애미", country: "미국", tz: "America/New_York" },
  { name: "Boston", country: "미국", tz: "America/New_York" },
  { name: "보스턴", country: "미국", tz: "America/New_York" },
  { name: "Washington DC", country: "미국", tz: "America/New_York" },
  { name: "워싱턴", country: "미국", tz: "America/New_York" },
  { name: "Atlanta", country: "미국", tz: "America/New_York" },
  { name: "애틀랜타", country: "미국", tz: "America/New_York" },
  { name: "Las Vegas", country: "미국", tz: "America/Los_Angeles" },
  { name: "라스베가스", country: "미국", tz: "America/Los_Angeles" },
  { name: "Toronto", country: "캐나다", tz: "America/Toronto" },
  { name: "토론토", country: "캐나다", tz: "America/Toronto" },
  { name: "Vancouver", country: "캐나다", tz: "America/Vancouver" },
  { name: "밴쿠버", country: "캐나다", tz: "America/Vancouver" },
  { name: "Montreal", country: "캐나다", tz: "America/Toronto" },
  { name: "몬트리올", country: "캐나다", tz: "America/Toronto" },
  { name: "Mexico City", country: "멕시코", tz: "America/Mexico_City" },
  { name: "멕시코시티", country: "멕시코", tz: "America/Mexico_City" },
  { name: "Honolulu", country: "미국 (하와이)", tz: "Pacific/Honolulu" },
  { name: "호놀룰루", country: "미국 (하와이)", tz: "Pacific/Honolulu" },
  { name: "Anchorage", country: "미국 (알래스카)", tz: "America/Anchorage" },
  { name: "앵커리지", country: "미국 (알래스카)", tz: "America/Anchorage" },

  // Americas - South/Central
  { name: "São Paulo", country: "브라질", tz: "America/Sao_Paulo" },
  { name: "상파울루", country: "브라질", tz: "America/Sao_Paulo" },
  { name: "Rio de Janeiro", country: "브라질", tz: "America/Sao_Paulo" },
  { name: "리우데자네이루", country: "브라질", tz: "America/Sao_Paulo" },
  { name: "Buenos Aires", country: "아르헨티나", tz: "America/Argentina/Buenos_Aires" },
  { name: "부에노스아이레스", country: "아르헨티나", tz: "America/Argentina/Buenos_Aires" },
  { name: "Santiago", country: "칠레", tz: "America/Santiago" },
  { name: "산티아고", country: "칠레", tz: "America/Santiago" },
  { name: "Bogota", country: "콜롬비아", tz: "America/Bogota" },
  { name: "보고타", country: "콜롬비아", tz: "America/Bogota" },
  { name: "Lima", country: "페루", tz: "America/Lima" },
  { name: "리마", country: "페루", tz: "America/Lima" },
  { name: "Caracas", country: "베네수엘라", tz: "America/Caracas" },
  { name: "카라카스", country: "베네수엘라", tz: "America/Caracas" },

  // Oceania
  { name: "Sydney", country: "호주", tz: "Australia/Sydney" },
  { name: "시드니", country: "호주", tz: "Australia/Sydney" },
  { name: "Melbourne", country: "호주", tz: "Australia/Melbourne" },
  { name: "멜버른", country: "호주", tz: "Australia/Melbourne" },
  { name: "Brisbane", country: "호주", tz: "Australia/Brisbane" },
  { name: "브리즈번", country: "호주", tz: "Australia/Brisbane" },
  { name: "Perth", country: "호주", tz: "Australia/Perth" },
  { name: "퍼스", country: "호주", tz: "Australia/Perth" },
  { name: "Auckland", country: "뉴질랜드", tz: "Pacific/Auckland" },
  { name: "오클랜드", country: "뉴질랜드", tz: "Pacific/Auckland" },
];
